Fix testcases that depends on triton
Error:
```
>       fp16_matmul.skip_autotune()
E       AttributeError: 'NoneType' object has no attribute 'skip_autotune'

ops/transformer/inference/test_attention.py:37: AttributeError
```
due to fp16_matmul is None when deepspeed.HAS_TRITON is False

Signed-off-by: Artem Kuzmitckii <artem.kuzmitckii@amd.com>