Fix compilation of Evoformer (#7862)
`EvoformerAttnBuilder` returns instances of `Path` from `include_paths`
which then cause failures in `OpBuilder.builder` when passing them to
`strip_empty_entries` that calls `len` on them which isn't defined for
`Path` instances:
>   TypeError: object of type 'PosixPath' has no len()

Fixes regression introduced in #7760

cc @sdvillal

Signed-off-by: Alexander Grund <alexander.grund@tu-dresden.de>
Signed-off-by: nathon-lee <leejianwoo@gmail.com>